# def calculate(a,b):
#     sum=a+b
#     print(sum)
# calculate(10,20)
# calculate(10,2)

# average:
# def average(a,b,c):
#     sum=(a+b+c)
#     avg= sum/3
#     print(avg)
# average(23,23,34)

# si
# def simple(p,r,t):
#     simple_int=(p*r*t)/100
#     print(simple_int)
# simple(20000,10.24,7)


# def demo():
#     a=10
#     b=20
#     print(locals())
# demo()


# def test():
#     x=100
#     print(locals()["x"])
# test()

# can we modify local variables using locals()
# def test():
#     x=10
#     locals()['x']=100
#     print(x)
# test()

# # global identifiers
# country="russia"
# def display():
#     name="jay"
#     print(name)
#     print(country)
# display()

# modify global variable: 
# x=5
# globals()['x']=40
# print(x)

